SELECT
    T1.HOUR ,
    COUNT (T2.DATETIME) AS COUNT
FROM (
      SELECT LEVEL-1 AS HOUR 
      FROM DUAL 
      CONNECT BY LEVEL<25
     ) T1
LEFT JOIN ANIMAL_OUTS T2
ON T1.HOUR = TO_CHAR(T2.DATETIME, 'HH24')
GROUP BY HOUR
ORDER BY HOUR