-- 코드를 입력하세요
SELECT
      T1.ANIMAL_ID
    , T1.ANIMAL_TYPE
    , T1.NAME

FROM ANIMAL_OUTS T1
LEFT JOIN ANIMAL_INS T2
ON T1.ANIMAL_ID = T2.ANIMAL_ID

where T2.SEX_UPON_INTAKE not like T1.SEX_UPON_OUTCOME 
ORDER BY T1.ANIMAL_ID ASC;